name: Build and Deploy to Azure Container Apps

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: <your-registry-name>.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t <your-registry-name>.azurecr.io/discordchecklistbot:latest .
          docker push <your-registry-name>.azurecr.io/discordchecklistbot:latest

      - name: Azure CLI Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Container Apps
        run: |
          az containerapp create --name discordchecklistbot --resource-group <your-resource-group> \
          --environment <your-containerapps-environment> --image <your-registry-name>.azurecr.io/discordchecklistbot:latest \
          --target-port 8000 --ingress 'external' --env-vars DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }} APPINSIGHTS_INSTRUMENTATIONKEY=${{ secrets.APPINSIGHTS_INSTRUMENTATIONKEY }}
